GET localhost:5000

### USERS

# Register a user
POST localhost:5000/api/users

### AUTHORIZATION

# Get logged-in user
GET localhost:5000/api/auth

###

# Auth user & get token
POST localhost:5000/api/auth

### CONTACTS

# Get all users contacts
GET localhost:5000/api/contacts

###

# Add new contacts contact
POST localhost:5000/api/contacts

###

# Update contact
PUT localhost:5000/api/contacts/1

###

# Delete contact
DELETE localhost:5000/api/contacts/1
